export const FETCHING_LIBRARY_DATA = 'FETCHING_LIBRARY_DATA';
export const FETCHING_LIBRARY_DATA_SUCCESS = 'FETCHING_LIBRARY_DATA_SUCCESS';
export const FETCHING_LIBRARY_DATA_FAIL = 'FETCHING_LIBRARY_DATA_FAIL';

export const SELECT_LIBRARY_ITEM = 'SELECT_LIBRARY_ITEM';
export const DESELECT_LIBRARY_ITEM = 'DESELECT_LIBRARY_ITEM';

export const EMAIL_CHANGED ='EMAIL_CHANGED';
export const PASSWORD_CHANGED ='PASSWORD_CHANGED';
export const LOGIN_USER = 'LOGIN_USER';


